version: '2'

services:
  db:
    container_name: db
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "guruten"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-use-native-aio=0
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/mysqld_charset.cnf:/etc/mysqld_charset.cnf
  
  backend:
    container_name: go
    tty: true
    build:
      context: ./
      dockerfile: ./docker/go/Dockerfile
    ports:
      - "4000:4000"
    command: /bin/bash
    volumes:
      - ./:/guruten

  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    environment:
      TZ: Asia/Tokyo
    ports:
      - "80:80"
      - "443:443"
    links:
      - "backend"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
